In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import json

In [3]:
user_emb = tf.constant([-0.116804, -0.314196, -0.628917, 0.0147506, 0.243619, 0.4848, -0.127038, 0.0912797,
                        -0.0973673, -0.320615, 0.187426, -0.00600598, -0.226693, 0.230844, 0.105143, 0.28843,
                        0.583322, 0.388846, -0.030855, -0.236351, -0.429838, 0.354583, 0.126397, 0.604772, -0.408072,
                        0.0176221, -0.106141, 0.34593, -0.159998, 0.291105, -0.237833, -0.306905])

In [8]:
tf.tensordot(user_emb, user_emb, 1)

<tf.Tensor: shape=(), dtype=float32, numpy=2.9726908>

In [20]:
temp = tf.concat([user_emb[tf.newaxis], user_emb[tf.newaxis]], 0)

In [14]:
user_emb[tf.newaxis]

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[-0.116804  , -0.314196  , -0.628917  ,  0.0147506 ,  0.243619  ,
         0.4848    , -0.127038  ,  0.0912797 , -0.0973673 , -0.320615  ,
         0.187426  , -0.00600598, -0.226693  ,  0.230844  ,  0.105143  ,
         0.28843   ,  0.583322  ,  0.388846  , -0.030855  , -0.236351  ,
        -0.429838  ,  0.354583  ,  0.126397  ,  0.604772  , -0.408072  ,
         0.0176221 , -0.106141  ,  0.34593   , -0.159998  ,  0.291105  ,
        -0.237833  , -0.306905  ]], dtype=float32)>

In [18]:
rand_mat = tf.random.uniform((8, 32))

In [22]:
tf.linalg.matmul(temp, rand_mat, transpose_b=True)

<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[ 0.7870761 ,  0.44722086,  0.10719401,  1.4440676 ,  0.21252304,
         0.52408886, -0.23285323, -0.19227147],
       [ 0.7870761 ,  0.44722086,  0.10719401,  1.4440676 ,  0.21252304,
         0.52408886, -0.23285323, -0.19227147]], dtype=float32)>

In [26]:
keys_tensor = tf.constant(['a', 'b', 'c'])
vals_tensor = tf.constant([[7,9], [8,9], [9,9]])
input_tensor = tf.constant(['a', 'f'])
table = tf.lookup.StaticHashTable(
    tf.lookup.KeyValueTensorInitializer(keys_tensor, vals_tensor),
    default_value=-1)
table.lookup(input_tensor).numpy()


InvalidArgumentError: Expected shape [3] for value, got [3,2] [Op:LookupTableImportV2]

In [24]:
table.lookup(tf.constant('a'))

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [29]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
tf.gather(params, indices=1).numpy()

array([10., 11., 12.], dtype=float32)